### ISSUE TITLE
Emojis in defconfig crash apps

### ISSUE THREAD

**Issue by groozchique** [PrimoDev23/android_kernel_xiaomi_sdm660#1]
I know that it's cool, but **emojis** in your defconfig will cause crashes for apps like `Google Drive` or `McDonalds`.
Please, don't do that unless you want to cause your users an asspain and waste your time figuring out what's wrong.
https://github.com/PrimoDev23/android_kernel_xiaomi_sdm660/blob/90e62bfb7622e4b20f72abf538fc756d85992d64/arch/arm64/configs/whyred_defconfig#L3

**Comment by SantiagoPintos** [comment]
“it just works™”

**Comment by Kugumin** [comment]
Already fixed for next release, which definitely will be soon
